apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: shared
spec:
  gatewayClassName: cilium

  infrastructure:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-type: "REGIONAL"
  
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All