sources:
  - gateway-httproute

domainFilters:
  - brenner.santos.nom.com

policy: sync

registry: txt

txtOwnerId: kubernetes

provider:
  name: webhook

  webhook:
    image:
      repository: ghcr.io/amoniacou/external-dns-digitalocean-webhook
      pullPolicy: IfNotPresent

    env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: digitalocean-dns
            key: DO_TOKEN

    service:
      port: 8080